### ISSUE TITLE
will it work during development?

### ISSUE THREAD

**Issue by paulvi** [andersonkyle/stackoverflow-q37862552#1]
will it work during development?

**Comment by andersonkyle** [comment]
If you are referring to a Live Reload development workflow then you'll likely need to leverage another tool such as Gulp to watch for changes in Web-Library (css, javascript, etc.) and then copy them to Web-App/target/classes/ See this for more detail: [npmjs.com/package/gulp-watch](https://www.npmjs.com/package/gulp-watch)
